version: '3.8'

services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/src
    ports:
      - "3000:3000"
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
    - postgres_data:/var/lib/postgressql/data

  redis:
    image: redis:latest
    restart: always

volumes:
  postgres_data:
