version: '3.8'

services:
  app:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/app
    ports:
      - "3000:3000"
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgressql/data
    env_file:
      - .env


  redis:
    image: redis:latest
    restart: always

volumes:
  postgres_data:
